[package]
name = "token-mill-v2-client"
version = { workspace = true }
edition = { workspace = true }

[lib]
test = false
doctest = false

[dependencies]
solana-program = "2.2.1"
borsh = "1.5.7"
num-derive = "0.4.2"
num-traits = "0.2.19"
thiserror = "2.0.12"
